spring:
  cloud:
    gateway:
      routes:
        - id: delivery-app
          uri: lb://DELIVERY-APP
          predicates:
            - Path=/delivery/**
          filters:
            - AuthenticationFilter


        - id:  restaurant-app
          uri: lb://RESTAURANT-APP
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

  application:
    name: resturant-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      instance:
        hostname: localhost


