spring.application.name=security-service
server.port=8081
spring.profiles.active=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/users_info
spring.datasource.username=postgres
spring.datasource.password=root
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=10000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=security-service
spring.cache.redis.time-to-live=60000

