server:
  port: 8081

spring:
  application:
    name: security-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

      instance:
        hostname: localhost
