# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: delivery-service
    name: delivery-service
    namespace: default
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: delivery-service
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: delivery-service
        spec:
            containers:
                - image: 911191919191/delivery-service:V7
                  imagePullPolicy: Always
                  name: delivery-service
                  envFrom:
                      - configMapRef:
                          name: resturant-service
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
status:
    availableReplicas: 1
    conditions:
        - lastTransitionTime: "2025-05-25T22:51:27Z"
          lastUpdateTime: "2025-05-25T22:51:27Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
        - lastTransitionTime: "2025-05-25T22:51:20Z"
          lastUpdateTime: "2025-05-25T22:51:27Z"
          message: ReplicaSet "delivery-service-d9764765b" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1

---

# ConfigMap definition
apiVersion: v1
kind: ConfigMap
metadata:
    creationTimestamp: "2025-05-26T04:41:46Z"
    name: resturant-service
    namespace: default
    resourceVersion: "92616"
    uid: bdaec6b6-c0b3-4305-bd47-adf1c632562b
data:
    RESTURANT_SERVICE_URL: http://192.168.49.2:32731
