services:
  delivery-service:
    build:
      context: /home/samyog/samyog/Restaurant-Management-System/delivery-service  # Directory where the Dockerfile is located
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - currency-network

networks:
  currency-network:
    driver: bridge
