apiVersion: v1
kind: Service
metadata:
    creationTimestamp: "2025-05-25T22:54:10Z"
    labels:
        app: delivery-service
    name: delivery-service
    namespace: default
    resourceVersion: "84072"
    uid: db7d34c5-2382-45af-89f5-b55836f89ec1
spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.106.79.59
    clusterIPs:
        - 10.106.79.59
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - nodePort: 31246
          port: 8082
          protocol: TCP
          targetPort: 8082
    selector:
        app: delivery-service
    sessionAffinity: None
    type: LoadBalancer
status:
    loadBalancer: {}
