apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-05-24T00:13:54Z"
  generation: 1
  labels:
    app: security-services
  name: security-services
  namespace: default
  resourceVersion: "69765"
  uid: c0b64fb0-de7c-40a2-8176-13fc7ada408b
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: security-services
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: security-services
    spec:
      containers:
      - image: 911191919191/security-service:V1
        imagePullPolicy: IfNotPresent
        name: security-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T00:13:54Z"
    lastUpdateTime: "2025-05-24T00:14:05Z"
    message: ReplicaSet "security-services-6bcf7bdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-25T15:20:04Z"
    lastUpdateTime: "2025-05-25T15:20:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
