version: "3.8"

services:
  security-service:
    build:
      context: /home/samyog/samyog/Restaurant-Management-System/security-service
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - postgres  # Add dependency on PostgreSQL
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_info
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  naming-server:
    build:
      context: /home/samyog/samyog/Restaurant-Management-System/service-registry
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_info
    ports:
      - "5432:5432"
    networks:
      - currency-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  currency-network:
    driver: bridge

volumes:
  pgdata:
