server:
  port: 8082

spring:
  application:
    name: delivery-app

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      instance:
        hostName: localhost


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    enabled: true
    endpoint: http://localhost:9411/api/v2/spans
    service-name: delivery-app

logging:
  pattern:
    level: "%5p [${spring.application.name: },%X{traceId:-},%X{spanId:-}]"


